AppIngE/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', ListaPosts.as_view(), name='home'),
    path('about/', about, name='about'),
    path('registro/', register, name='registro'),
    path('ingresar/', login_request, name='ingresar'),
    path('cerrarSesion/', logout_request, name='cerrarSesion'),
    path('perfil/', perfil, name='perfil'),
    path('editarPerfil/', editarPerfil, name='editarPerfil'),
    path('agregarAvatar/', agregarAvatar, name='agregarAvatar'),
    path('posteos/', CrearPosteos.as_view(), name='posteos'),
    path('detallePost/<slug:slug>/', DetallePosts.as_view(), name='detallePost'),
    path('actualizarPost/<slug:slug>/',
         ActualizarPosteos.as_view(), name='actualizarPost'),
    path('borrarPost/<slug:slug>/', BorrarPosteos.as_view(), name='borrarPost'),
]

IngEBlog/urls.py
from django.contrib import admin
from django.urls import path, include
# Para imágenes
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppIngE.urls')),
    path('mensajeria/', include('AppMensajeria.urls'))
]
# Para imágenes
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'AppIngE.views.error_403'
handler404 = 'AppIngE.views.error_404'
handler500 = 'AppIngE.views.error_500'

AppIngE/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.urls import reverse


#Avatar
class Avatar(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to='avatares', null=True, blank= True)


#Posteos
class Posteo(models.Model):
    titulo= models.CharField(max_length=500, unique=True)
    slug=models.SlugField(max_length=500, unique=True)
    subtitulo=models.CharField(max_length=500)
    imagen=models.ImageField(upload_to='Imagen', null=True, blank=False)
    contenido=RichTextField()
    autor=models.ForeignKey(User, on_delete=models.CASCADE, related_name='posteos')
    actualizacion=models.DateTimeField(auto_now=True)
    creacion=models.DateTimeField(auto_now_add=True)
    
    class Meta: 
        ordering = ['-creacion']

    def get_absolute_url(self):
        return reverse('detallePost', kwargs={'slug':self.slug})
    
    def __str__(self):
        return self.titulo

AppIngE/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

# Creación de usuario

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label='Nombre de usuario')
    email=forms.EmailField()
    password1=forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2=forms.CharField(label='Confirmar contraseña', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields=['username', 'email', 'password1', 'password2']
        help_text={k:"" for k in fields}

# Edición de usuario

class UserEditForm(UserCreationForm):
    email=forms.EmailField(label="Modificar E-mail")
    password1=forms.CharField(label='Cambiar contraseña', widget=forms.PasswordInput)
    password2=forms.CharField(label='Confirmar nueva contraseña', widget=forms.PasswordInput)
    first_name = forms.CharField(label='Modificar nombre')
    last_name = forms.CharField(label='Modificar apellido')

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2', 'first_name', 'last_name']
        help_texts = {k:"" for k in fields}

#Avatar 
class AvatarFormulario(forms.Form):
    imagen=forms.ImageField(label="Imagen")

# Posteos

# -Crear posteos-

class CrearPosteoForm(forms.ModelForm):
    class Meta:
        model=Posteo
        fields=['titulo', 'subtitulo', 'imagen', 'contenido']
        labels={ "titulo":"Título", "subtitulo":"Subtítulo", "imagen":"Imagen", "contenido":"Contenido"}

# -Para postear una imagen-

class ImagenPosteoForm(forms.Form):
    imagen=forms.ImageField(label="Imagen")

AppIngE/views.py
from multiprocessing import context
from django.shortcuts import render
from .forms import *
from .models import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import redirect
# Creación de usuario


def error_403(request, exception):
    return render(request, '403.html')


def error_404(request, exception):
    return render(request, '404.html')


def error_500(request, *args, **argv):
    return render(request, '500.html')


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            usuario = form.cleaned_data['username']
            contraseña = form.cleaned_data['password1']
            user = authenticate(username=usuario, password=contraseña)
            login(request, user)
        return redirect('perfil')
    else:
        form = UserRegisterForm()
    return render(request, "register.html", {"form": form})

# inicio de sesión


def login_request(request):

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            usuario = form.cleaned_data.get('username')
            contrasena = form.cleaned_data.get('password')
            user = authenticate(username=usuario, password=contrasena)

            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                return render(request, "login.html", {"mensaje": "Los datos ingresados son incorrectos"})
        else:
            return render(request, "login.html", {"mensaje": "Formulario erróneo. Por favor, intentelo nuevamente."})
    else:
        form = AuthenticationForm()
        return render(request, "login.html", {'form': form})


@login_required
def logout_request(request):
    logout(request)
    return redirect('ingresar')

# Edición de perfil


@login_required
def editarPerfil(request):
    usuario = request.user
    if request.method == 'POST':
        miFormulario = UserEditForm(request.POST)
        if miFormulario.is_valid():
            usuario.email = miFormulario.cleaned_data['email']
            usuario.password1 = miFormulario.cleaned_data['password1']
            usuario.password2 = miFormulario.cleaned_data['password2']
            usuario.first_name = miFormulario.cleaned_data['first_name']
            usuario.last_name = miFormulario.cleaned_data['last_name']
            usuario.save()
            return redirect('perfil')
    else:
        miFormulario = UserEditForm(instance=usuario)
    return render(request, 'editarPerfil.html', {'miFormulario': miFormulario, 'usuario': usuario, 'imagen': getAvatar(request)})

# Perfil


@login_required
def perfil(request):
    usuario = request.user
    return render(request, 'profile.html', {'usuario': usuario, 'imagen': getAvatar(request), 'posteos': Post(request)})


def Post(request):
    posteos = Posteo.objects.filter(autor=request.user)
    if len(posteos) != 0:
        posteo = posteos
    else:
        posteo = 0
    return posteo

# Avatar


@login_required
def agregarAvatar(request):
    if request.method == 'POST':
        miFormulario = AvatarFormulario(request.POST, request.FILES)
        if miFormulario.is_valid():
            avatarViejo = Avatar.objects.filter(user=request.user)
            if (len(avatarViejo) > 0):
                avatarViejo.delete()
            avatar = Avatar(user=request.user,
                            imagen=miFormulario.cleaned_data['imagen'])
            avatar.save()
            return redirect('perfil')
    else:
        miFormulario = AvatarFormulario()
    return render(request, "agregarAvatar.html", {"miFormulario": miFormulario})


def getAvatar(request):
    avatarList = Avatar.objects.filter(user=request.user)
    if len(avatarList) != 0:
        img = avatarList[0].imagen.url
    else:
        img = 0
    return img

# About


def about(request):
    return render(request, 'about.html')

# Posteos

# Lista de Posts en el inicio.


class ListaPosts(generic.ListView):
    queryset = Posteo.objects.all().order_by('-creacion')
    template_name = 'home.html'

# Detalle Posts


class DetallePosts(generic.DetailView):
    model = Posteo
    template_name = 'DetallePosts.html'

# Crear Posteos


class CrearPosteos(LoginRequiredMixin, generic.CreateView):
    def get(self, request, *args, **kwargs):
        context = {'miFormulario': CrearPosteoForm()}
        return render(request, 'posts.html', context)

    def post(self, request, *args, **kwargs):
        miFormulario = CrearPosteoForm(request.POST, request.FILES)
        if miFormulario.is_valid():
            posteo = miFormulario.save(commit=False)
            posteo.autor = self.request.user
            slug = posteo.titulo
            posteo.slug = slug.replace(' ', '_').lower()
            posteo.save()
            return redirect(reverse_lazy('detallePost', args=[posteo.slug]))
        return render(request, 'posts.html', {'miFormulario': miFormulario})

# Actualización del post


class ActualizarPosteos(generic.UpdateView):
    model = Posteo
    fields = ['titulo', 'subtitulo', 'imagen', 'contenido']
    labels = {"titulo": "Título", "subtitulo": "Subtítulo",
              "imagen": "Imagen", "contenido": "Contenido"}
    template_name = 'actualizacionPosteo.html'


# Eliminar el post
class BorrarPosteos(generic.DeleteView):
    model = Posteo
    success_url = reverse_lazy('home')
    template_name = "borrarPosteo.html"

AppIngE/templates/DetallePosts.html
{% extends 'head.html' %} {% load static %} {% block titulo %}
<title>IngE · {{ posteo.titulo }}</title>
{% endblock %} {% block encabezado %}
<header>
    <h1 class="site-heading text-center text-faded d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3"
        >{{ posteo.titulo }}</span
      >
      <span class="site-heading-lower">IngE</span>
    </h1>
  </header>
{% endblock %} {% block principal %}
<main style="display: flex; justify-content: center">
  <div class="col-md-8 card mb-4 mt-3 left top">
    <div class="card-body">
      <h1 class="text-muted">{{ posteo.titulo }}</h1>
      <h2 class="text-muted">{{ posteo.subtitulo }}</h2>
      <p class="text-muted">{{ posteo.autor }} | {{ posteo.creacion }}</p>
      <img
        style="max-height: 500px; min-height: 250px"
        src="{{ posteo.imagen.url }}"
      />
      <p class="card-text">{{ posteo.contenido|safe }}</p>
    </div>
  </div>
</main>
{% endblock %}

AppIngE/templates/about.html
{% extends 'head.html' %} {% load static %} {% block titulo %}
<title>IngE · Sobre mi</title>
{% endblock %} {% block encabezado %}
<header>
  <h1 class="site-heading text-center text-faded d-none d-lg-block">
    <span class="site-heading-upper text-primary mb-3">Sobre mi</span>
    <span class="site-heading-lower">IngE</span>
  </h1>
</header>
{% endblock %} {% block principal %}
<main style="display: flex; justify-content: center">
  <div
    class="col-md-8 card mb-4 mt-3 left top"
    style="background-color: rgba(230, 167, 86, 0.9)"
  >
    <h1 style="text-align: center; color: #fa7600">
      ¡Hola! Te cuento un poco sobre mi...
    </h1>
    <p style="text-align: center; color: white; font-family: sans-serif">
      Mi nombre es Florencia, tengo 23 años y soy estudiante de Ingeniería
      Química.
    </p>
    <p
      style="
        margin-bottom: 0px;
        text-align: center;
        color: white;
        font-family: sans-serif;
      "
    >
      Este blog surge como proyecto final de un curso de Python de CoderHouse,
    </p>
    <p
      style="
        margin-bottom: 0px;
        text-align: center;
        color: white;
        font-family: sans-serif;
      "
    >
      del cual decidí participar debido a que, en la actualidad, saber programar
      es muy importante.
    </p>
    <p style="text-align: center; color: white; font-family: sans-serif">
      Y con las nuevas tecnologías considero que será muy útil para aplicarlo a
      mi carrera..
    </p>
    <p style="text-align: center; color: white; font-family: sans-serif">
      Espero que les guste y les sea útil.
    </p>
    <p style="text-align: center; color: white; font-family: sans-serif">
      ¡Saludos!
    </p>
  </div>
</main>
{% endblock %}

AppIngE/templates/actualizacionPosteo.html
{% extends 'head.html' %} {% load static %} {% block titulo %}
<title>IngE · Actualizar Post</title>
{% endblock %} {% block encabezado %}
<header>
    <h1 class="site-heading text-center text-faded d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">actualizar post</span>
      <span class="site-heading-lower">IngE</span>
    </h1>
  </header>
{% endblock %} {% block principal %}
<main style="display: flex; justify-content: center">
  <section class="page-section clearfix">
    <div class="container">
      <div
        class="intro-text left-0 text-center bg-faded p-5 rounded"
        style="
          background-color: rgba(230, 167, 86, 0.9);
          margin-top: 0px;
          max-width: auto;
        "
      >
        <form
          style="display: flex; flex-direction: column; justify-content: center"
          method="POST"
          enctype="multipart/form-data"
        >
          {% csrf_token %}
          <table>
            {{ form.media }} {{ form.as_table }}
          </table>
          <button style="margin: 20px 0px" type="submit">ACTUALIZAR</button>
        </form>
      </div>
    </div>
  </section>
</main>
{% endblock %}

AppIngE/templates/agregarAvatar.html
{% extends 'head.html' %} {% load static %} {% block titulo %}
<title>IngE · Cambiar Avatar</title>
{% endblock %} {% block encabezado %}
<header>
  <h1 class="site-heading text-center text-faded d-none d-lg-block">
    <span class="site-heading-upper text-primary mb-3">Agregar Avatar</span>
    <span class="site-heading-lower">IngE</span>
  </h1>
</header>
{% endblock %} {% block principal %}
<main>
  <section class="page-section clearfix">
    <div class="container">
      <div
        class="intro-text left-0 text-center bg-faded p-5 rounded"
        style="
          background-color: rgba(230, 167, 86, 0.9);
          margin-top: 0px;
          max-width: auto;
        "
      >
        <form
          action="{% url 'agregarAvatar' %}"
          method="POST"
          enctype="multipart/form-data"
        >
          {% csrf_token %}
          <table>
            {{ miFormulario.as_table }}
          </table>
          <button type="submit">AÑADIR</button>
        </form>
      </div>
    </div>
  </section>
</main>
{% endblock %}

AppIngE/templates/borrarPosteo.html
{% extends 'head.html' %} {% load static %} {% block titulo %}
<title>IngE · Borrar Post</title>
{% endblock %} {% block encabezado %}
<header>
  <h1 class="site-heading text-center text-faded d-none d-lg-block">
    <span class="site-heading-upper text-primary mb-3">Borrar post</span>
    <span class="site-heading-lower">IngE</span>
  </h1>
</header>
{% endblock %} {% block principal %}
<main style="display: flex; justify-content: center">
  <section class="page-section clearfix">
    <div class="container">
      <div
        class="intro-text left-0 text-center bg-faded p-5 rounded"
        style="
          background-color: rgba(230, 167, 86, 0.9);
          margin-top: 0px;
          max-width: auto;
        "
      >
        <form
          style="display: flex; flex-direction: column; justify-content: center"
          method="post"
        >
          {% csrf_token %}
          <p>¿Estás seguro que quieres eliminar el post "{{ object }}"?</p>
          <button style="margin: 20px 0px" type="submit">
            ELIMINAR PERMANENTEMENTE
          </button>
        </form>
      </div>
    </div>
  </section>
</main>
{% endblock %}

AppIngE/templates/editarPerfil.html
{% extends 'head.html' %} {% load static %} {% block titulo %}
<title>IngE · Editar Perfil</title>
{% endblock %} {% block encabezado %}
<header>
  <h1 class="site-heading text-center text-faded d-none d-lg-block">
    <span class="site-heading-upper text-primary mb-3">Editar Perfil</span>
    <span class="site-heading-lower">IngE</span>
  </h1>
</header>
{% endblock %} {% block principal %}
<main>
  <section class="page-section clearfix">
    <div class="container">
      <div
        class="intro-text left-0 text-center bg-faded p-5 rounded"
        style="
          background-color: rgba(230, 167, 86, 0.9);
          margin-top: 0px;
          max-width: auto;
        "
      >
        <h2
          style="
            font-weight: normal;
            margin-bottom: 20px;
            font-size: 15px;
            display: flex;
            justify-content: center;
          "
        >
          *Su nombre de usuario ({{ user.username }}) no puede ser modificado,
          en caso de necesitarlo, comuníquese con un administrador.
        </h2>
        <div style="display: flex; justify-content: center">
          {% if imagen %}
          <img style="height: 150px; width: 150px" src="{{ imagen }}" />
          <a
            href="{% url 'agregarAvatar' %}"
            style="
              background: beige;
              cursor: pointer;
              border: 2px solid black;
              text-align: center;
              height: 25px;
              font-size: 15px;
              margin-top: 125px;
            "
            >CAMBIAR IMAGEN</a
          >
          {% else %}
          <img
            style="height: 150px; width: 150px"
            src="{% static 'assets/img/avatar/defaultAvatar.jpg' %}"
          />
          <a
            href="{% url 'agregarAvatar' %}"
            style="
              background: beige;
              cursor: pointer;
              border: 2px solid black;
              text-align: center;
              height: 25px;
              font-size: 15px;
              margin-top: 125px;
            "
            >CAMBIAR IMAGEN</a
          >
          {% endif %}
        </div>
        <div style="display: flex; justify-content: center">
          <form action="{% url 'editarPerfil' %}" method="POST">
            {% csrf_token %}
            <table style="margin: 20px 0px">
              {{ miFormulario.as_table }}
            </table>
            <button
              style="
                background: beige;
                cursor: pointer;
                border: 2px solid black;
                text-align: center;
                width: 464px;
              "
              type="submit"
            >
              CONFIRMAR CAMBIOS
            </button>
          </form>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}

AppIngE/templates/head.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <style type="text/css">
      a:link,
      a:visited,
      a:active {
        text-decoration: none;
      }
    </style>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    {% block titulo %}
    <title>IngE · head</title>
    {% endblock %}
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'assets/favicon.ico' %}"
    />
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i"
      rel="stylesheet"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
  </head>
  <body>
    {% block encabezado %} {% endblock %}
    <nav
      class="navbar navbar-expand-lg navbar-dark py-lg-4"
      id="mainNav"
      style="background-color: #fa7600"
    >
      <div class="container">
        <a
          class="navbar-brand text-uppercase fw-bold d-lg-none"
          href="{% url 'home' %}"
          >IngE Blog</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase" href="{% url 'home' %}"
                >Inicio</a
              >
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase" href="{% url 'about' %}"
                >Sobre mi</a
              >
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase" href="{% url 'posteos' %}"
                >Postear</a
              >
            </li>
            {% comment %} <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase"
                >Bienvenido, {{user.username}}!!!.</a
              >
            </li> {% endcomment %}
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase" href="{% url 'perfil' %}"
                >Perfil</a
              >
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase" href="{% url 'mensajeria' %}"
                >Chat</a
              >
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase" href="{% url 'cerrarSesion' %}"
                >Cerrar Sesión</a
              >
            </li>
            {% else %}
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase" href="{% url 'ingresar' %}"
                >Iniciar sesión</a
              >
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase" href="{% url 'registro' %}"
                >Registrate!</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% block principal %} {% endblock %}
  </body>
</html>

AppIngE/templates/home.html
{% extends 'head.html' %} {% load static %} {% block titulo %}
<title>IngE · Home</title>
{% endblock %} {% block encabezado %}
<header>
  <h1 class="site-heading text-center text-faded d-none d-lg-block">
    <span class="site-heading-upper text-primary mb-3"
      >Un blog para ingenieros</span
    >
    <span class="site-heading-lower">IngE</span>
  </h1>
</header>
{% endblock %} {% block principal %}
<section class="page-section clearfix">
  <div class="container">
    <div
      class="intro-text left-0 text-center bg-faded p-5 rounded"
      style="background-color: rgba(230, 167, 86, 0.9); margin-top: 0px; max-width: auto"
    >
      {% for posteo in posteo_list %}
      <div style="display: flex; flex-direction: column; justify-content: left">
        <div
          style="
            display: flex;
            flex-direction: column;
            border: 3px solid black;
            margin: 0px 0px 10px 10px;
          "
        >
          <a href="{% url 'detallePost' posteo.slug %}">
            <div style="display: flex; flex-direction: row; color: black">
              <div>
                <h2>{{ posteo.titulo }}</h2>
                <h3 style="font-weight: normal">{{ posteo.subtitulo }}</h3>
                <h4 style="font-weight: normal">
                  {{ posteo.autor }} | {{ posteo.creacion }}
                </h4>
              </div>
              <div>
                <img
                  style="height: 125px; margin: 10px 10px 10px 50px"
                  src="{{ posteo.imagen.url }}"
                />
              </div>
            </div>
          </a>
        </div>
      </div>
      {% empty %}
      <h2 style="margin: 0px; padding: 10px">
        Aún no hay posts, se el primero!
      </h2>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

AppIngE/templates/login.html
{% extends 'head.html' %} {% load static %}
<head>
  {% block titulo %}
  <title>IngE · Iniciar sesión</title>
  {% endblock %}
</head>
{% block encabezado %}
<header>
  <h1 class="site-heading text-center text-faded d-none d-lg-block">
    <span class="site-heading-upper text-primary mb-3"
      >¡Inicia sesión y comparte!</span
    >
    <span class="site-heading-lower">IngE</span>
  </h1>
</header>
{% endblock %} {% block principal %}
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner bg-faded text-center rounded">
          <h2 class="section-heading mb-5">
            <span class="section-heading-lower">Inicia sesión</span>
          </h2>
          <form
            style="display: flex; flex-direction: column; justify-content: left"
            action="{% url 'ingresar' %}"
            method="POST"
          >
            {% csrf_token %}
            <table style="margin: 0px 0px 20px 0px">
              {{ form.as_table }}
            </table>
            <button type="submit">Iniciar sesión</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

AppIngE/templates/posts.html
{% extends 'head.html' %} {% load static %} {% block titulo %}
<title>IngE · Postear</title> {% endblock titulo %} {% block encabezado %}
<header>
  <h1 class="site-heading text-center text-faded d-none d-lg-block">
    <span class="site-heading-upper text-primary mb-3">Postear</span>
    <span class="site-heading-lower">IngE</span>
  </h1>
</header>
{% endblock %} {% block principal %}
<mai style="display: flex; justify-content: center">
  <section class="page-section clearfix">
    <div class="container">
      <div
        class="intro-text left-0 text-center bg-faded p-5 rounded"
        style="
          background-color: rgba(230, 167, 86, 0.9);
          margin-top: 0px;
          max-width: auto;
        "
      >
        <div style="margin: 10px">
          <form
            action="{% url 'posteos' %}"
            method="POST"
            enctype="multipart/form-data"
          >
            {% csrf_token %}
            <table>
              {{ miFormulario.media }} {{ miFormulario.as_table }}
            </table>
            <button type="submit">CREAR!</button>
          </form>
        </div>
      </div>
    </div>
  </section>
</mai>
{% endblock principal %}

AppIngE/templates/register.html
{% extends 'head.html' %} {% load static %} {% block titulo %}
<title>IngE · Registrarse</title>
{% endblock %} {% block encabezado %}
<header>
  <h1 class="site-heading text-center text-faded d-none d-lg-block">
    <span class="site-heading-upper text-primary mb-3"
      >¡Registrate y empieza a ser parte!</span
    >
    <span class="site-heading-lower">IngE</span>
  </h1>
</header>
{% endblock %} {% block principal %}
<section class="page-section cta">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner bg-faded text-center rounded">
                     <h2 class="section-heading mb-5">
                        <span class="section-heading-lower">Registrarse</span>
                    </h2>
                    <p class="address mb-5">
                        <form style="display: flex; flex-direction: column; justify-content: right" action="{% url 'registro' %}"method="POST">
                        {% csrf_token %} 
                            {{ form.as_p }}
                            <button type="submit">Registrarse!</button>
                        </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}